### ISSUE TITLE
Import statements are being printed on the same line

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#103]

**Comment by jvcoutinho** [comment]
Requires investigation

**Comment by guilhermejccavalcanti** [comment]
A pretty printer bug? Try the old pretty printer.

Em seg, 9 de set de 2019 19:24, João Victor <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
Yes. My guess is that between the old and the current S3M version there was a change that messed up with the imports line breaks.
Currently, S3M seems to not print the imports on the same line.

**Comment by pauloborba** [comment]
why hasn't this bug failed our regression tests?

**Comment by jvcoutinho** [comment]
All of S3M's tests (except for the new indentation and spacing tests) ignore whitespaces when asserting results.

**Comment by pauloborba** [comment]
why is this a good idea? especially considering that pretty printing and indentation handling is reasonably stable...

**Comment by pauloborba** [comment]
@guilhermejccavalcanti @jvcoutinho ?

**Comment by guilhermejccavalcanti** [comment]
This PR https://github.com/guilhermejccavalcanti/jFSTMerge/pull/106 addresses the issue?

**Comment by jvcoutinho** [comment]
> This PR #106 addresses the issue?

No. I believe this was an issue for an older version of S3M.
What do you think about S3M's tests ignoring whitespaces in their assertions?

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti instead of storing a merge file to validate the test?

**Comment by guilhermejccavalcanti** [comment]
what do you mean "storing a merge file to validate the test"? We actually
use the fields MergeContext.semistructuturedOutput which is used for others
things too.

When we are not testing the indentation, I think it is ok to ignore them in
the assertions.

Em ter, 17 de set de 2019 às 08:28, João Victor <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
The idea was to use the semistructuredOutput field to compare with the
expected output stored in a file.

This would capture the indentation problem with the imports since we didnt
have a test for that.

Em ter, 17 de set de 2019 17:39, Guilherme Cavalcanti <
notifications@github.com> escreveu:
