### ISSUE TITLE
Cryptography is ciphering partially

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#104]
As described by @guilhermejccavalcanti -- still requires investigation

**Comment by pauloborba** [comment]
@guilhermejccavalcanti do you have further details about this?

**Comment by guilhermejccavalcanti** [comment]
This is a random error, hard (no to mention "impossible") to predict and
reproduce.
When I commented the body of this method
https://github.com/guilhermejccavalcanti/jFSTMerge/blob/master/src/main/java/br/ufpe/cin/crypto/CryptoUtils.java#L61
on my experiments, it solved the problem. So this might be the starting
point.

Em qua, 11 de set de 2019 às 17:11, Paulo Borba <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
Devo enviar um PR sobre isso em breve. Mas seria interessante discutir alguns pontos que eu notei, sob a ótica de alguém que estudou criptografia.

Primeiro, sobre a utilidade. Pelo que entendo, a criptografia serve como prevenção para que os usuários da ferramenta não alterem os arquivos de estatísticas, que servirão como análises futuras. Sendo assim, um sistema criptográfico de integridade (como assinatura digital) seria mais útil como substituto ou complementar ao atual sistema de sigilo. Um atacante ainda pode alterar o puro-texto (texto original) mesmo não sabendo nada sobre ele sem um sistema de integridade.

Depois, sobre vulnerabilidades. Algumas práticas tornam a criptografia bem vulnerável a ataques (não sei até que ponto isso é realmente necessário, porém):
- A chave é fixa, e não gerada aleatoriamente, para todas as cifragens. Isso em especial torna o sistema bem vulnerável a um ataque. 
- O modo CBC é um modo de cifras de bloco que usa o resultado da cifra do bloco anterior como chave para a próxima cifra. Nós usamos ele. Porém, a primeira chave, chamada de IV (_initialization vector_), deve ser aleatória e deve ser armazenada junto com o cifrotexto para que o lado da decriptação possa decifrar o primeiro bloco do texto. Isso não acontecia antes, então é possível que essa tenha sido a causa dessa issue (o primeiro bloco do texto não era decriptografado corretamente). 
- Finalmente, haviam várias decifragens e cifragens um tanto desnecessárias no código. Eu tentei simplificar no início e no fim da execução do programa.
Eu corrigi esses pontos de vulnerabilidade acima. Porém, como efeito colateral do primeiro ponto, o tempo de execução do S3M deve aumentar.

**Comment by pauloborba** [comment]
excelente análise @jvcoutinho!
