### ISSUE TITLE
testes completamente automatizados, com opção de rodar todos os testes e sumarizar as respostas

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#11]

**Comment by pauloborba** [comment]
implementar mais testes (como os de encoding)

**Comment by pauloborba** [comment]
falta melhorar os testes, bem mais

precisamos também de uns testes de performance (testar a performance da criptografia).

**Comment by jvcoutinho** [comment]
Implementei alguns testes de encoding. Os testes tentam fazer merge com arquivos ASCII, UTF-8 e UTF-16, separadamente. O output foi OK, mas vale a pena dizer que o encoding dos arquivos do 3º teste (UTF-16) fazem eles serem tratados como binários, implicando que o merge só conta o número de bytes aumentados ao invés de detectar conflito.

**Comment by pauloborba** [comment]
boa @jvcoutinho! o resultado esperado do teste com UTF-16 seria conflito mesmo, ou o texto resultante. se não for, o teste deve quebrar até que a gente ajeite essa funcionalidade de trabalhar bem com encodings diferentes.

**Comment by jvcoutinho** [comment]
Implementei os testes com a família ISO-8859. Eles falham.

**Comment by jvcoutinho** [comment]
Também fiz um teste pra quando a similaridade dos arquivos é muito alta (mudando letras), mas passível de conflito. A ferramenta não detectou conflito (falso negativo), mas o merge padrão do Git detectou.

**Comment by pauloborba** [comment]
@jvcoutinho sobre os testes da família ISO-8859, ótimo. pode enviar o PR.

sobre esse teste de similaridade, podemos discutir melhor no slack. mas, a princípio, a similaridade não implica em conflito.

**Comment by jvcoutinho** [comment]
Implementei testes para arquivos diferentes de Java (C++ e Typescript), direcionados para quando o suporte a essas linguagens for implementado.

**Comment by pauloborba** [comment]
@jvcoutinho esses testes de C++ e Typescript não devem falhar hoje. o teste deve passar arquivos C++ e Typescript para a ferramenta e verificar que o resultado do s3m é o mesmo gerado pelo merge não estruturado. foi isso que você fez?

**Comment by pauloborba** [comment]
@jvcoutinho da uma melhorada nos testes que voce fez para que, alem de verificar o resultado do merge, eles verifiquem também se os arquivos de log foram corretamente atualizados, OK?

**Comment by jvcoutinho** [comment]
Ok!

Em ter, 14 de ago de 2018 11:05, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
OK @guilhermejccavalcanti, mas não entendi o contexto do teu comentário. eu não estava assumindo que o textual não daria problema de encoding.

**Comment by guilhermejccavalcanti** [comment]
Ah, beleza. Eu tinha entendido isso. Eheh

Em ter, 14 de ago de 2018 11:28, Paulo Borba <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
A implementação da checagem dos arquivos de log foi feita.

**Comment by jvcoutinho** [comment]
Também implementei uma opção de rodar todos os testes de shell (bastando digitar shunit2 s3mTests.sh), mas há várias possibilidades para isso, seria interessante discutir mais.
O próximo passo é refatorar os testes de shell e fazer a opção de rodar todos os testes de JUnit.

**Comment by jvcoutinho** [comment]
Os testes de shell foram refatorados.

**Comment by pauloborba** [comment]
boa @jvcoutinho. discutimos na segunda. você pensou também nos testes de performance (comentado mais acima)?

**Comment by jvcoutinho** [comment]
Eu coloquei verificações nos testes para verificar se a criptografia está
funcionando corretamente. Há algo mais a ser testado, como tempo ou coisas
desse tipo?

Em sex, 17 de ago de 2018 11:41, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
sim, tempo mesmo. isso seria o teste de performance. da uma olhada no livro de ES.

**Comment by jvcoutinho** [comment]
Ok!

Em 17 de ago de 2018 12:11 PM, "Paulo Borba" <notifications@github.com>
escreveu:

sim, tempo mesmo. isso seria o teste de performance. da uma olhada no livro
de ES.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/guilhermejccavalcanti/jFSTMerge/issues/11#issuecomment-413897070>,
or mute the thread

**Comment by jvcoutinho** [comment]
Verificar encoding do sistema operacional/código

**Comment by jvcoutinho** [comment]
Verificar se os testes de encoding estão com os resultados corretos e entender o porquê.

**Comment by jvcoutinho** [comment]
Diferença de tempo entre merge com criptografia e merge sem criptografia = 10%.

**Comment by jvcoutinho** [comment]
Criar teste para saber se a saída do log é correta com repositório grande e múltiplos merges.

**Comment by guilhermejccavalcanti** [comment]
@jvcoutinho os shelltestes dependem do jFSTMerge.jar daqui https://github.com/guilhermejccavalcanti/jFSTMerge/tree/master/testfiles/shelltests/config que é uma copia do que tá aqui https://github.com/guilhermejccavalcanti/jFSTMerge/tree/master/binary

esse processo é manual, o que pode levar à inconsistências. Tenta configurar os testes pra pegar diretamente o jar daqui https://github.com/guilhermejccavalcanti/jFSTMerge/tree/master/binary evitando essa duplicação por favor.

**Comment by guilhermejccavalcanti** [comment]
valeu!

**Comment by jvcoutinho** [comment]
Melhorei o teste de performance da criptografia (com - sem = 10%)
e implementei um teste de shell pra verificar a corretude das estatísticas com um merge em um repositório grande.

O teste verifica os dados do arquivo jfstmerge.summary, como x JAVA files, y false positive(s), z false negative(s)...

**Comment by pauloborba** [comment]
com - sem <= 10%, certo @jvcoutinho?

**Comment by jvcoutinho** [comment]
Isso! Nem me liguei que coloquei = no comentário

**Comment by jvcoutinho** [comment]
Está quase tudo pronto, só tem um detalhe. Os testes de performance não passam com 10% (não sei dizer se isso é devido à solução que eu dei ao problema que reportei no Slack ou ao Gradle, perdão).
O que vocês sugerem que eu faça?

**Comment by jvcoutinho** [comment]
Eu tive uma ideia provavelmente mais eficiente e mais correta, de simplesmente apagar os arquivos de log antes de iniciar o teste. Vou tentar fazer isso.

**Comment by pauloborba** [comment]
1. @jvcoutinho sobre os 10%, aumentando para 15% estaria OK? 

2. cada teste realmente deve ter um set-up e um clear up bem definido. 

3. agora, apagar o arquivo de log no inicio é um teste de uma situação atípica, que provavelmente só acontecerá quando a ferramenta for usada pela primeira vez, não? 

4. se for o caso, no início do teste você deveria copiar um arquivo de log com conteúdo X, após o teste verificar se o conteúdo do arquivo foi alterado como deveria, e ao final copiar o arquivo original, deiando o ambiente intacto

**Comment by jvcoutinho** [comment]
1. Não. O resultado do teste fica inconsistente em menos de 30%.

3. Sim. É que eu notei que o teste sempre executa se o arquivo "problemático" não está lá. Mas irei fazer a cópia, sim.

**Comment by pauloborba** [comment]
@guilhermejccavalcanti sobre a criptografia, a tarefa de descriptografar está no bloco static de uma classe. qual a motivação para isso? a hipótese atual, sendo investigada por @jvcoutinho, é que a tarefa de descriptografar é realizada quando a classe é carregada, o primeiro teste executado criptografa o arquivo antes descriptografado, e, por isso, o segundo teste (que precisa ler o arquivo descriptografado) não passa

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti o teste gera aquela exceção do bloco (CryptoException) ao tentar descriptografar o arquivo statistics. Esse é o stack trace da criptografia.
[erro.txt](https://github.com/guilhermejccavalcanti/jFSTMerge/files/2340424/erro.txt)

**Comment by guilhermejccavalcanti** [comment]
@pauloborba  não lembro exatamente porque descriptografo num bloco estático. Isso é uma mudança minha até recente. Provavelmente foi algo que me deparei quando rodei o s3m em alguma mostra, e vi essa necessidade.

Mas também a um fator performance ai: descriptografar num único lugar uma única fez é mais eficiente do que varias vezes, uma em cada método, sob demanda como está atualmente. Daniel Maida tinha notado isso quando implementou a criptografia.


@jvcoutinho  e @pauloborba  o que eu não entendo é por que não havia este problema antes? Esse teste a que paulo se refere é novo? Foi tu que fez agora? Se sim, tá explicado: era um bug que não tinhamos conhecimento. Mas caso esse teste já existia antes, ele não quebrava, e portanto o problema é outro.

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti sim, eu o fiz agora. Esse deve ser o primeiro teste que desativa a criptografia antes de um merge, então é possível que haja um bug sim.

**Comment by pauloborba** [comment]
@jvcoutinho quem falha? a criptografia? por que falha?

**Comment by pauloborba** [comment]
@guilhermejccavalcanti sabes explicar?

**Comment by guilhermejccavalcanti** [comment]
sempre que o serviço de criptografia lança qualquer erro (CryptoException), os logs antigos são renomeados para uma versão logX_defect e um novo log é criado (logX) e criptografado com o conteúdo novo. ele só faz uma vez pra evitar um loop infinito de tentativa e erro.

agora porque isso tá afetando os testes não faço ideia. Talvez ele esteja lendo o log esperando o valor X, mas como deu erro e foi necessário criar um log novo, o valor tá Y?

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti na verdade eu creio que isso só afete o tempo. Foi a explicação para aumentar a margem de tempo entre o merge com criptografia e o merge sem criptografia.
Eu creio que quando o método é chamado novamente, o tempo entre os dois merges dá um salto, fazendo o teste não passar. O problema é medir esse salto, porque é inconsistente. De qualquer modo, eu ficarei de olho nisso.
