### ISSUE TITLE
CryptoException when running AllHandlersTest.java

### ISSUE THREAD

**Issue by guilhermejccavalcanti** [guilhermejccavalcanti/jFSTMerge#116]
@jvcoutinho I updated my local version of S3M to the last one, deleted the folder .jfstmerge to avoid garbage from older versions, and executed AllHandlersTest.java. That is my typical workflow when updating the source code. However, this time I got that exception:

![image](https://user-images.githubusercontent.com/3333981/67299324-e38cd080-f4c2-11e9-96b4-15cb743f47cd.png)

**Comment by guilhermejccavalcanti** [comment]
I had to disable crypto (-c false).

**Comment by jvcoutinho** [comment]
I believe this was a configuration error on your PC.

**Comment by jvcoutinho** [comment]
Can we close this issue?

**Comment by pauloborba** [comment]
@guilhermejccavalcanti?

**Comment by guilhermejccavalcanti** [comment]
I still have the issue.

Em sáb., 2 de nov. de 2019 às 11:41, Paulo Borba <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti can you check if there's an update for your Java 8 version?

**Comment by guilhermejccavalcanti** [comment]
eu formatei o PC por outras razões, e ao reinstalar funcionou. 
De qualquer modo, era importante saber a causa disso.

**Comment by jvcoutinho** [comment]
Eu acredito que era algo relacionado a uma sub versão do Java.

Em qui, 28 de nov de 2019 20:42, Guilherme Cavalcanti <
notifications@github.com> escreveu:

**Comment by guilhermejccavalcanti** [comment]
Então seria importante colocar no readme a versão Java recomendada. Em
breve informo aqui a versão que tou usando.

Em sáb, 30 de nov de 2019 às 13:55, João Victor <notifications@github.com>
escreveu:

**Comment by guilhermejccavalcanti** [comment]
Atualizei o readme com a versão que tou usando, provavelmente algumas
versões anteriores também devem funcionar, mas por vida das dúvidas
coloquei a minha que é a mais atual hoje.

Em sáb., 30 de nov. de 2019 às 18:32, Guilherme Cavalcanti <gjcc@cin.ufpe.br>
escreveu:
