### ISSUE TITLE
Merge Methods and Check References renaming handlers are duplicating abstract methods

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#122]
Case: https://github.com/jvcoutinho/merge-tools/tree/master/s3m-handlers-analysis/jsoup/c850608f18d6cf71d96713abed84def85f5bb8fe/src/main/java/org/jsoup/nodes/Node.java

**Comment by guilhermejccavalcanti** [comment]
@jvcoutinho não tenho acesso a esse teu repo privado, e consequentemente o exemplos

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti @pauloborba vou explicar por aqui mesmo

O caso foi que todos os métodos abstratos na base deram match com o 1º em left e right, devido à condição de mesmo corpo, causando uma duplicação no fim.

Sugiro um dos seguintes pontos:
-  criar um match especial pra métodos abstratos, possivelmente apenas com as condições de mesma assinatura **ou** mesma assinatura exceto o nome **ou** mesma assinatura exceto os argumentos
- remover métodos abstratos das condições que checam o corpo

Além disso, poderíamos adicionar a condição "mesma assinatura exceto os argumentos" na atual de "corpo similar e mesma assinatura exceto o nome", também. Tornaria o match mais preciso.

**Comment by pauloborba** [comment]
faz sentido tratar métodos abstratos de forma diferente, e não como um método concreto com corpo vazio
