### ISSUE TITLE
Check Textual and Keep Both Methods renaming handlers failed to delete a method

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#123]
Case: https://github.com/jvcoutinho/merge-tools/tree/master/s3m-handlers-analysis/dubbo/9f5cc83d34e1eee3ca11fd6113767e5f5630d394/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/filter/FutureFilter.java

Left and right removed the same method, but CT and KB maintained them. This probably is related to the superimposition and not to the handlers.

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti @pauloborba it's a superimposition bug

see the following example, equivalent to the one in the link:

**BASE**
```
public class Test {

    public void method(String a, int b) {

    }
    
}
```

**LEFT/RIGHT**: deleted `method(String, int)` and added an inner class containing a method having the same signature than one in base (plus some irrelevant changes to differentiate left from right)
```
public class Test {
    
    public class InnerTest {
        
        public String method(String a, int b) {
            return "";
        }
    }
    
}
```

**S3M** - no renaming handlers, hasn't deleted `method(String, int)`
```
public class Test {

    public class InnerTest {
        
        public String method(String a, int b) {
            return "";
        }
        
    }

    public void method(String a, int b) {

    }
    
}
```

**Comment by jvcoutinho** [comment]
Of course, the main procedure is to fix the bug. But the superimposition code's technical debt is too high at the moment, making it difficult to even detect the bug (or to solve it without breaking everything)... It may require a refactoring.

**Comment by pauloborba** [comment]
@jvcoutinho does that happen whenever two developers delete the same method? or is it specific to situations with inner classes?

**Comment by jvcoutinho** [comment]
@pauloborba specific to inner classes

**Comment by pauloborba** [comment]
hum! @guilhermejccavalcanti inner classes are handled by superimposition or by a special handler?
