### ISSUE TITLE
--ignore-space-change flag for all situations

### ISSUE THREAD

**Issue by guilhermejccavalcanti** [guilhermejccavalcanti/jFSTMerge#133]
Seems like that the --ignore-space-change flag is used only when unstructured merge is invoked. So, it is necessary to check and apply the flag to all kinds of conflict and situations.

**Comment by guilhermejccavalcanti** [comment]
When merging the triple: 
![image](https://user-images.githubusercontent.com/3333981/78589449-96a17a00-7816-11ea-8917-cb3925e5ed7b.png)

There is no difference besides the blank lines. I was expecting that  the flag --ignore-space-change would work for that, but it does not, and there is still a merge conflict:
![image](https://user-images.githubusercontent.com/3333981/78589629-e41de700-7816-11ea-84e9-b4f92f86c5df.png)

So I suspected the flag was not working, or even not reaching all merging situation. However, when merging the same triple directly via git, invoking git's own flag, the result was the same:
![image](https://user-images.githubusercontent.com/3333981/78589961-71613b80-7817-11ea-91e7-fc967b3e56e1.png)

The git manual says that _"[...]the option ignores whitespace completely when comparing lines[...]"_
I believe that they strictly consider whitespace, not including blank lines as in the example. 

So, in principle, we have two options:
1.  Assume that this is correct, and leave as it is.
2.  Build upon that and include blank lines.

What do you think @pauloborba @jvcoutinho ?

**Comment by pauloborba** [comment]
excellent point @guilhermejccavalcanti! 

I believe that we should keep the git behavior, and explicitly explain that in the text that explains the flag --ignore-space-change 

But have you tried the git option -Xignore-space-change too? I believe this should be the option we should use (look for ignore-space-change here https://git-scm.com/docs/git-diff) for comparison purposes.

Deleting a line doesn't seem to be considered a space change.

**Comment by guilhermejccavalcanti** [comment]
> But have you tried the git option -Xignore-space-change too? I believe this should be the option we should use (look for ignore-space-change here https://git-scm.com/docs/git-diff) for comparison purposes.

Same merge conflict with that option.
