### ISSUE TITLE
Initialization Blocks Multiple Handler (-hibmb/--handle-initialization-blocks-multiple-blocks) is not present in the S3m.jar

### ISSUE THREAD

**Issue by leosoftlima** [guilhermejccavalcanti/jFSTMerge#157]
Execution command: 

jar s3m.jar <left.java> <base.java> <right.java> -o <outuput_file> -hib true ( ok, working correctly)

Problem: 
jar s3m.jar <left.java> <base.java> <right.java> -o <outuput_file> -hibmb true ( not present, not working)

jar s3m.jar <left.java> <base.java> <right.java> -o <outuput_file> -hibmb (not present, not working)

**Comment by leonardoAnjos16** [comment]
@leosoftlima, testasse com a versão mais recente do **jar** (`binary/jFSTMerge.jar`). Testei aqui e funcionou com `-hibmb true` 🤔

**Comment by leosoftlima** [comment]
> @leosoftlima, have you tried it with the most recent version of the **jar** file (`binary/jFSTMerge.jar`). I've tested it with `-hibmb true` and it worked 🤔

I'm using the s3m.jar of the project miningframework/dependencies  - the problem is present reference lib.

**Comment by leonardoAnjos16** [comment]
> I'm using the s3m.jar of the project miningframework/dependencies - the problem is present reference lib.
Alright, I'll update the jar here and there (miningframework/dependencies)
