### ISSUE TITLE
Versão com com handler de renaming que mantém os dois métodos

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#17]

**Comment by pauloborba** [comment]
implementar deletion/renaming handler para metodos e construtores

**Comment by pauloborba** [comment]
![image](https://user-images.githubusercontent.com/1207332/43801620-07465582-9a6a-11e8-80ed-299b31c741cc.png)

**Comment by pauloborba** [comment]
olhar 5e5fe36c027e892d1b579d7b77cb4d633952d0e6

**Comment by gaabs** [comment]
Apenas confirmando, seriam esses dois casos abaixo?

![image](https://user-images.githubusercontent.com/8092225/44437586-3a320e00-a591-11e8-8df1-c2422598cd84.png)

![image](https://user-images.githubusercontent.com/8092225/44437656-81b89a00-a591-11e8-895e-7619ee4171f1.png)

**Comment by pauloborba** [comment]
@gaabs no primeiro exemplo, o caso 3 do slide, que acho mais interessante, daria como resultado a classe com apenas public void n(){int a;}. o que a sua figura ilustra, no primeiro exemplo, seria o caso 2 do slide.

**Comment by pauloborba** [comment]
@gaabs o segundo exemplo é interessante. acredito que deveria dar conflito, ao invés de duplicar o método.

**Comment by guilhermejccavalcanti** [comment]
Esse segundo exemplo é o que chamamos de "mutual renaming". O handler
também trata,  teoricamente.

Em qua, 22 de ago de 2018 15:31, Paulo Borba <notifications@github.com>
escreveu:

**Comment by gaabs** [comment]
É que pelo título dessa issue ("Versão com com handler de renaming que mantém os dois métodos"), eu tinha entendido que a ideia era implementar a opção 2 do slide ("manter dois elementos, um com nome original e corpo alterado e outro com nome alterado e corpo original")

**Comment by pauloborba** [comment]
Tem razão. A outra opção seria relacionada a outra issue. Queremos implementar as duas e compará-las

**Comment by pauloborba** [comment]
@pauloborba reduced FNs (by checking new method calls) could also be FPs in case the new calls are not actually executed or do not have external observation effect

**Comment by guilhermejccavalcanti** [comment]
So this handler only conflicts in the presence of new method calls?
Otherwise It keeps both declarations?

Em qui, 6 de set de 2018 11:31, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
I guess so. New calls to the renamed method. Doesn't it make sense to you?

**Comment by guilhermejccavalcanti** [comment]
It is ok.

Em qui, 6 de set de 2018 às 14:11, Paulo Borba <notifications@github.com>
escreveu:

**Comment by guilhermejccavalcanti** [comment]
@gaabs where is the check for new method calls mentioned above?
I could not find it.

**Comment by gaabs** [comment]
@guilhermejccavalcanti , I have not added this check yet. I plan to add this soon. 
Does the current code already has a function for similar purposes?

**Comment by guilhermejccavalcanti** [comment]
More or less, you can see here:
https://github.com/guilhermejccavalcanti/jFSTMerge/blob/master/src/main/java/br/ufpe/cin/mergers/handlers/DeletionsHandler.java#L226
It uses Eclipse JDT.
That implementation only searches for references on the same class. A
complete search should look for references in all files.

Em seg, 10 de set de 2018 às 21:02, Giovanni Barros <
notifications@github.com> escreveu:

**Comment by gaabs** [comment]
@guilhermejccavalcanti , Is it really possible to check for references in all files involved on the merge be detected currently? As I understand, the current code merges each tuple of three files separately.

**Comment by guilhermejccavalcanti** [comment]
Gotcha! You just found the limitation. For experimental purposes, through the method ```mergeRevisions```, we can, but real use is not possible because of what you said.

**Comment by gaabs** [comment]
Is this a limitation of the tool itself, or is it about how git merge works?

**Comment by guilhermejccavalcanti** [comment]
how git merge works

**Comment by pauloborba** [comment]
@gaabs to be more precise, it's due to the way that we plug s3m into "git merge". we plug it as a git driver; not sure if this is the only kind (file level merge, not revision level) of merge driver we can plug. this seems to be the only way to plug, accordingly to previous studies from another collaborator.

**Comment by gaabs** [comment]
Are the below situations and corresponding conflict reports acceptable, @pauloborba ?
<pre>
// 1
When Left changed method body
And Right renamed method and corresponding calls
Then KeepBothMethods should not report conflict
And MergeMethods should not report conflict

// 2
When Left changed method body
And Right renamed method but forgot calls
Then KeepBothMethods should report conflict
And MergeMethods should not report conflict

// 3
When Left changed method body
And Right renamed method and added new call
Then KeepBothMethods should not report conflict
And MergeMethods should report conflict

// 4
When Left changed method body and added new call
And Right renamed method and corresponding calls
Then KeepBothMethods should not report conflict
And MergeMethods should not report conflict

// 5
When Left changed method body and added new call
And Right renamed method but forgot calls
Then KeepBothMethods should report conflict
And MergeMethods should not report conflict

// 6
When Left changed method body and added new call
And Right renamed method and added new call
Then KeepBothMethods should not report conflict
And MergeMethods should report conflict

**Comment by pauloborba** [comment]
@gaabs 1 OK, but maybe better to use "just"to make clear these are the only changes, as in "Left just  changed method body". In 2, why do you think that MergeMethods should not report conflict? We better discuss this in my office or via skype.

**Comment by pauloborba** [comment]
@gaabs OK. better to make descriptions slightly more precise.

**Comment by pauloborba** [comment]
@gaabs report conflicts involving only the method declarations, with reference to the calls or other elements that might be involved in the conflict too.

**Comment by pauloborba** [comment]
@gaabs 1. how often would the handlers be used (% merge scenarios, % conflicts) 2. how often KBM/MM correctly resolve renaming conflicts (reduce FPs)/ incorrectly resolve conflicts (add FNs)/ report conflict (keep the same result) 3. how does s3m+MM and s3m+KBM compare in terms of FPs and FNs when compared to unstructured merge (OOPSLA table)?

**Comment by pauloborba** [comment]
@gaabs verifica este cenário, por favor: Um desenvolvedor modifica o corpo do método edit(long key) e adiciona método selecionarFuncionario()
O outro desenvolvedor modifica o corpo do método edit(long key), remove o parâmetro do método edit() e adiciona os métodos delete() e selectEquipement()
Os métodos selectEquipement() e selecionarFuncionario() possuem o mesmo corpo.

O git apresenta um conflito do tipo cross cutting.
O s3m?

**Comment by pauloborba** [comment]
registrando possível bug no sentido de que o cálculo de similaridade está sendo chamado antes de confirmar o conflito.

registrando limitações na forma como a similaridade é detectada (comparar primeiro o header; só se for similar, compara o corpo), e na forma como as chamadas de método são procuradas (só com o nome, não com a assinatura completa). mais alguma coisa @gaabs?

**Comment by pauloborba** [comment]
@gaabs para cada cenário analisado, precisamos de resumo da mudanca de left, resumo da mudanca de right, resultado do handler 1 e do handler 2. quais seriam bons nomes para os handlers?

**Comment by gaabs** [comment]
> @gaabs verifica este cenário, por favor: Um desenvolvedor modifica o corpo do método edit(long key) e adiciona método selecionarFuncionario()
> O outro desenvolvedor modifica o corpo do método edit(long key), remove o parâmetro do método edit() e adiciona os métodos delete() e selectEquipement()
> Os métodos selectEquipement() e selecionarFuncionario() possuem o mesmo corpo.
> 
> O git apresenta um conflito do tipo cross cutting.
> O s3m?

@pauloborba, resultados abaixo. Espero que tenha entendido corretamente.

LEFT | BASE | RIGHT
![image](https://user-images.githubusercontent.com/8092225/47610098-50da6280-da23-11e8-9d07-dadc39a71d05.png)

S3M | Unstructured
![image](https://user-images.githubusercontent.com/8092225/47610152-5d12ef80-da24-11e8-9500-e1f6a98de96d.png)

**Comment by pauloborba** [comment]
@guilhermejccavalcanti olha a bronca! @jvcoutinho olha isso. @gaabs isso ocorre também com teus handlers?

**Comment by guilhermejccavalcanti** [comment]
@gaabs e @pauloborba  é o mesmo caso dessa issue, certo? https://github.com/guilhermejccavalcanti/jFSTMerge/issues/65

o handler faz matching de declarações provalvamente independentes. O algoritmo de similaridade textual aprova porque só tem uma linha, e as linhas são iguais.

**Comment by gaabs** [comment]
@guilhermejccavalcanti , não é exatamente o mesmo caso, uma vez que em #65 LEFT e RIGHT possuem exatamente os mesmo métodos no conflito. Mas, de fato, é um problema na detecção de mutual renaming, e é possível que uma solução só resolva ambos os casos. Talvez algo como uma verificação de similaridade com nós removidos também.

@pauloborba , acontece com o handler Merge Methods, uma vez que ele utiliza o mesmo código do s3m para mutual renaming. Para o handler Keep Both Methods, não, uma vez que ele mantém ambos.

**Comment by guilhermejccavalcanti** [comment]
Sim, acredito a solução de um resolve o outro também. Mas comparação
textual limita bastante. Sempre teremos esses casos de métodos de uma linha
que, pela assinatura, deduzimos que são coisas completamentes diferente,
mas textualmente são a mesma coisa.

Em dom, 28 de out de 2018 21:44, Giovanni Barros <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
@gaabs e @guilhermejccavalcanti (@jvcoutinho também): não entendo porque isso entraria em mutual renaming, já que apenas um dos desenvolvedores mudou a assinatura de um método QUE foi modificado por outro. ele deveria verificar que ainda há um método com a mesma assinatura do original e não entrar em mutual renaming.

arthur deu uma ideia interessante: ao inves de pegar similaridade da assinatura+corpo, a gente computar duas similaridade: uma da assinatura e outra do corpo... que tal?

**Comment by guilhermejccavalcanti** [comment]
provavelmente o handler tá mais flexível do que deveria. Há uma lista de
nós adicionados por left, e uma lista de nós adicionados por right. Pelo
que lembro, o handler então compara os nós de uma lista com os da outra,
então certamente compara mais coisa do que deveria para um caso de mutual
renaming. (@gaabs pode confirmar por favor).

A ideia de Arthur tá OK, mas apenas vai postergar um problema que é
inerente à comparação textual. É tipo o problema de encoding: rodamos essas
ferramentas a anos, em centenas de projetos de diferentes tipo e nunca
houve nada do tipo. Ai num específico de uma empresa, o negócio pipocou e
se tornou impraticável. Ai vai que num projeto muito especifico não só o
corpo dos métodos como a assinatura são similares, mesmo que sejam coisas
completamente diferentes?

Em seg, 29 de out de 2018 às 17:41, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
impossibilidade de eliminar problema não é motivo para não reduzir problema, @guilhermejccavalcanti

**Comment by gaabs** [comment]
@guilhermejccavalcanti é isso mesmo, ele apenas compara as listas de nós adicionados.

@pauloborba não sei se fui claro o bastante a respeito do que está acontecendo internamente. O problema não foi o fato do método ter sido alterado, mas sim o fato de métodos quase idênticos terem sido adicionados em cada lado. O exemplo abaixo ilustra isso melhor:

![image](https://user-images.githubusercontent.com/8092225/47762035-ae77e480-dc99-11e8-89ac-4d2c1cd3fa7c.png)

![image](https://user-images.githubusercontent.com/8092225/47762091-e717be00-dc99-11e8-9e25-6bd99008330a.png)

Tem dois pontos aí:
1. Isso é realmente desejado?
2. Isso deve ser detectado no handler de renaming?

**Comment by jvcoutinho** [comment]
Estive pensando em uma solução e testei no SemanticMerge pra confirmar se ele faz o que pensei. Como não há um método original na base (os métodos foram adicionados independentemente), creio que o handler de renaming não deveria atuar nesse caso. Atualmente, o handler compara todos os nós adicionados em left e right, sem se importar com a base.
O SemanticMerge não detecta renaming, mas duas adições:

![semantic](https://user-images.githubusercontent.com/27645414/47789815-6639e000-dcf4-11e8-9f59-7fad65c84422.png)

**Comment by pauloborba** [comment]
> On 30 Oct 2018, at 23:17, Giovanni Barros <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> @guilhermejccavalcanti <https://github.com/guilhermejccavalcanti> é isso mesmo, ele apenas compara as listas de nós adicionados.
> 
> @pauloborba <https://github.com/pauloborba> não sei se fui claro o bastante a respeito do que está acontecendo internamente. O problema não foi o fato do método ter sido alterado,
> 

@gaabs é que, se o método não tivesse sido alterado, não deveria haver conflito. se não tivesse sido alterado, não era nem para entrar no handler de renaming.

adicionar métodos com mesmo corpo e quase a mesma assinatura não deveria ser um problema, e não deveria ser detectado por ninguém.

**Comment by pauloborba** [comment]
sim, mais evidência de que temos um problema com a implementação atual

**Comment by pauloborba** [comment]
@jvcoutinho tudo isso aqui foi resolvido com tua última implementação? podemos fechar?

**Comment by jvcoutinho** [comment]
Sim, quando um nó não se encontra na base, o handler não trata como renaming. Podemos fechar.
