### ISSUE TITLE
Tratar adequadamente, e de forma eficiente, análise de encoding dos arquivos

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#20]

**Comment by pauloborba** [comment]
uma opção então seria verificar o encoding só uma vez por projeto git, não para todo merge. mas melhor discutirmos isso na próxima reunião, já que quero entender melhor a situação (ler um arquivo com encoding diferente não deveria influenciar no merge em geral, a nao ser na parte de espaçamento, por isso quero entender porque o resultado era vazio)

**Comment by jvcoutinho** [comment]
Eu vou fazer parte dessa issue para tratar o parâmetro de encoding.
