### ISSUE TITLE
Comparar com o merge estruturado

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#21]

**Comment by pauloborba** [comment]
@guilhermejccavalcanti definir principalmente com que frequencia as ferramentas diferem. e porque diferem. confirmar ou refutar a teoria. entender o algoritmo de linhas consecutivas de @prga

**Comment by pauloborba** [comment]
@guilhermejccavalcanti o que aprendemos com a comparação (implicações) que poderia ser usado para melhorar o s3m? implementar #67? algo mais?

**Comment by guilhermejccavalcanti** [comment]
Além de linhas consecutivas, é sempre ignorar espaçamentos por default (mas
dando a opção de parametro também).
De resto, as duas foram muito parecidas.

Em qui, 4 de jul de 2019 às 08:10, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
@guilhermejccavalcanti mas nas implications não têm algumas ideias que poderiam ser incorporadas?

**Comment by guilhermejccavalcanti** [comment]
Ah, sim. Pensei que se referia apenas a melhorias no semiestruturado.
Tem a outra estratégia lá de auto-tunning semi/strut, que já enxergo como
uma outra ferramenta.

Em qui, 4 de jul de 2019 às 13:00, Paulo Borba <notifications@github.com>
escreveu:
