### ISSUE TITLE
Aceitar parâmetros que adaptam várias funcionalidades

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#24]
- ativar ou desativar vários handlers
- ativar ou desativar logs, criptografia, etc.
- ativar ou desativar tratamento de encoding, etc.

**Comment by pauloborba** [comment]
Definir parâmetros para ativar/desativar a computação de  estatísticas e certas análises

**Comment by jvcoutinho** [comment]
Prioridade: encoding e espaçamento

**Comment by pauloborba** [comment]
yes

**Comment by jvcoutinho** [comment]
@pauloborba @guilhermejccavalcanti If spacing and encoding parameters are ok, it's time to implement new parameters now. Suggestions?

**Comment by guilhermejccavalcanti** [comment]
Peharps parameters for all the handlers?

Em ter, 11 de set de 2018 18:12, João Victor <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
One parameter to control all of them, you say? Because we're going to need a parameter for each handler, right?

**Comment by jvcoutinho** [comment]
You can tell me the parameters' names and their descriptions.

**Comment by guilhermejccavalcanti** [comment]
A parameter for each handler. Follow what @gaabs did with renaming.

Em ter, 11 de set de 2018 18:38, João Victor <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
@guilhermejccavalcanti please list here the current handler names, and what they do, so that I can refine the text so that @jvcoutinho can add that to the code/help. that's what he needs now.

**Comment by guilhermejccavalcanti** [comment]
DeletionsHandler.java - checks deletions of top level elements (e.g
innerclasses)
DuplicatedDeclarationHandler.java - checks if there are additions of two
declarations with the same identifier (statistics purpose only)
InitializationBlocksHandler.java  - checks if there are similar
initialization blocks
NewElementReferencingEditedOneHandler.java     - checks if added
declarations reference edited declarations
RenamingConflictsHandler.java - checks if methods and constructors are
renamed
TypeAmbiguityErrorHandler.java - checks if added imported declarations
leads to type ambiguity errors

You can find a detailed description of each handler on their JavaDoc.

Em qua, 12 de set de 2018 às 06:38, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
we should better discuss this a bit further through slack
