### ISSUE TITLE
automatizar criação de binários (instalação, ferramenta standalone, shelltests) 

### ISSUE THREAD

**Issue by guilhermejccavalcanti** [guilhermejccavalcanti/jFSTMerge#30]
Toda vez que atualizamos o código fonte do S3M, é necessário gerar um novo jar (vai pra pasta /binary), um novo instalador (vai pra pasta /installer). Os shelltestes são baseados no jar de /binary. Então teria que atualizar isso também.

Os shelltestes dependem do jFSTMerge.jar daqui https://github.com/guilhermejccavalcanti/jFSTMerge/tree/master/testfiles/shelltests/config que é uma copia do que tá aqui https://github.com/guilhermejccavalcanti/jFSTMerge/tree/master/binary

Esse processo é manual, o que pode levar à inconsistências. Tenta configurar os testes pra pegar diretamente o jar daqui https://github.com/guilhermejccavalcanti/jFSTMerge/tree/master/binary evitando essa duplicação 

Precisamos de uma forma automatizada de geração de binários.

**Comment by guilhermejccavalcanti** [comment]
@jvcoutinho na realidade é mais interessante mantermos esses binários num repositório à parte. Toda vez que commitamos os binários recebemos a seguite mensagem:

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File installer/s3mInstaller.jar is 75.25 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

Sem contar que deixa o projeto muito grande para só quem precisa do código fonte. Então, idealmente, o que precisamos é o seguinte.

1.  Mecanismo de geração automática de binários (o instalador e a ferramenta standlone).
2. Armazenamento em umrrepositório secundário desses binários
3. Apagar esses binários do repositório oficial
4. Geração automática do binário para a execução dos shelltests. @gaabs  já faz isso em https://github.com/guilhermejccavalcanti/jFSTMerge/pull/34 precisamos sincronizar isso

ok @pauloborba ?

**Comment by pauloborba** [comment]
@guilhermejccavalcanti se esse arquivo só é modificado de tempos em tempos, poderia deixar tudo no mesmo repositório mesmo, para eliminar um ponto de falha e simplificar a replicação. se é modificado frequentemente, aí faz mais sentido deixar em outro local mesmo

**Comment by guilhermejccavalcanti** [comment]
Esses arquivos devem ser modificados a qualquer alteração da ferramenta.

Em sex, 31 de ago de 2018 15:40, Paulo Borba <notifications@github.com>
escreveu:

**Comment by pauloborba** [comment]
então melhor colocar em outro local mesmo

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti @pauloborba eu posso adaptar a configuração do Gradle para copiar os binários para suas devidas pastas, ok? E sobre o repositório secundário, ele conterá sempre o último binário modificado, "espelhando" o código do repositório principal, é isso?

**Comment by guilhermejccavalcanti** [comment]
> eu posso adaptar a configuração do Gradle para copiar os binários para suas devidas pastas, ok?

como seria isso na prática? em que momento haveria essa criação e copia dos arquivos? Se liga também que o s3mInstaller.jar contém um s3m.jar (uma versão renomeado do jFSTMerge.jar). Então teria que abrir esse s3mInstaller.jar, e substituir o jar de dentro pelo novo, toda vez.

> E sobre o repositório secundário, ele conterá sempre o último binário modificado, "espelhando" o código do repositório principal, é isso?

isso, e o readme original tirando a parte referente a código.

**Comment by jvcoutinho** [comment]
Quando o Gradle faz um build, ele gera o binário dentro da pasta
build/libs. Eu apenas faria ele copiar esse binário para a pasta binary
(fazendo o git ignorar a pasta) ou para a home do usuário no fim do build.
Isso para o jFSTMerge.jar. Pro s3mInstaller tenho que ver com + calma.

Em ter, 18 de set de 2018 15:06, Guilherme Cavalcanti <
notifications@github.com> escreveu:

**Comment by guilhermejccavalcanti** [comment]
Entendi, ainda assim, não seria 100% automático, né, pois temos que nos lembrar de gerar a build do gradle pra pegar os jars? @gaabs fez algo automático no momento de execução do travis, num foi?

**Comment by jvcoutinho** [comment]
Ah, cê quer que os jars sejam pegos do repositório secundário? No caso,
deve ter algum mecanismo que verifique se a sua versão é a mais atualizada,
né?

Eu pensei na build do Gradle pq dps de modificar o código tem q passar por
ela, mas eu creio q essa funcionalidade não é pros desenvolvedores e sim
pros usuários, certo?

Em ter, 18 de set de 2018 16:34, Guilherme Cavalcanti <
notifications@github.com> escreveu:

**Comment by guilhermejccavalcanti** [comment]
Não, não. Não tenho preferência não. O que tou querendo saber se há como deixar isso totalmente automático, pois a build do gradle é manual, ou tou errado?

**Comment by jvcoutinho** [comment]
Cê digita "gradle build" no cmd ou pela IDE e ele faz tudo pra vc, compila
tudo, gera os binários e roda os testes

Em 18 de set de 2018 6:06 PM, "Guilherme Cavalcanti" <
notifications@github.com> escreveu:

Não, não. Não tenho preferência não. O que tou querendo saber se há como
deixar isso totalmente automático, pois a build do gradle é manual, ou tou
errado?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/guilhermejccavalcanti/jFSTMerge/issues/30#issuecomment-422555012>,
or mute the thread

**Comment by jvcoutinho** [comment]
Para usar o novo recurso, basta digitar
`git lfs install --skip-smudge`
na linha de comando. Esse parâmetro fará o git lfs não fazer download nos binários.

**Comment by pauloborba** [comment]
@jvcoutinho onde informacoes como essa acima aparecem no readme/codigo para ajudar a quem quiser colaborar com o desenvolvimento do sistema? é importante documentar bem para reduzir a barreira de colaboracao com o projeto

**Comment by jvcoutinho** [comment]
@pauloborba posso atualizar o README com as mudanças feitas até agora, pode ser?

**Comment by pauloborba** [comment]
sim, por favor

**Comment by pauloborba** [comment]
@jvcoutinho mas temos efetivamente uma situação dessa, de querer atualizar um arquivo que é um alias para outro arquivo?

**Comment by jvcoutinho** [comment]
Sim, isso é visível nos repositórios locais.
Uma abordagem mais certeira é gerar o binário do 0, ao invés de atualizar apenas um arquivo dentro.

**Comment by pauloborba** [comment]
@guilhermejccavalcanti and @gaabs any opinion on that?

**Comment by jvcoutinho** [comment]
@phmb Eu pensei em outra abordagem, que foi baixar o jar do instalador antes de fazer o update. O comando `git lfs pull` faz isso, e é rápido.
