### ISSUE TITLE
Order of revisions currently not respected on renamings

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#35]
Currently, the tool is giving the same results for renaming, independently of which revision is on left and which revision is on right, swapping "MINE" and "YOURS" annotations on some cases.

In other words, merging LEFT BASE RIGHT gives the same result as merging RIGHT BASE LEFT.

Observed scenario:

Base File
```
public class Test {	
	public void m()	{
	}
}
```

Left File
```
public class Test {	
	public void m()	{
		int a;
	}
}
```

Right File
```
public class Test {
	public void n()	{
	}
}
```

Merge output for both merges:
```
public  class  Test {
	
<<<<<<< MINE
public void m()	{
		int a;
	}

=======
public void n()	{

	}
>>>>>>> YOURS

}
```

**Comment by guilhermejccavalcanti** [comment]
You can probably fix that here https://github.com/guilhermejccavalcanti/jFSTMerge/blob/master/src/br/ufpe/cin/mergers/handlers/RenamingConflictsHandler.java#L165 and here https://github.com/guilhermejccavalcanti/jFSTMerge/blob/master/src/br/ufpe/cin/mergers/handlers/RenamingConflictsHandler.java#L191

**Comment by pauloborba** [comment]
@gaabs which s3m version have you used? the one that uses the handler that keeps the two method versions?

**Comment by gaabs** [comment]
I have used the version that is currently on the master branch. I already have spotted the bug cause and will solve it soon. It was just a wrong parameter being passed to the `generateRenamingConflict` method.

**Comment by pauloborba** [comment]
@guilhermejccavalcanti and @gaabs I was wondering why the commit message has the declaration of method n, instead of blank.

**Comment by guilhermejccavalcanti** [comment]
It probably detected the counterpart via textual similarity.
The declarations are too small, so it easily fits in the 70% degree of
similarity adopted by the handler.

Em ter, 28 de ago de 2018 às 10:33, Paulo Borba <notifications@github.com>
escreveu:
