### ISSUE TITLE
Fix JavaCC encoding 

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#40]
as detected by @leoribeiro36, to improve FN analysis (of both tools), and FP analysis of the unstructured tool

**Comment by pauloborba** [comment]
@guilhermejccavalcanti has this been fixed?

**Comment by guilhermejccavalcanti** [comment]
in this pull request https://github.com/guilhermejccavalcanti/jFSTMerge/pull/47 ,ok @jvcoutinho ?
