### ISSUE TITLE
Basic renaming handler might add FNs

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#52]
when one developer renames a declaration and changes its body, and the other developer changes the body of the same declaration, in the same area.

**Comment by pauloborba** [comment]
@gaabs is this kind of situation captured by your renaming handlers?

**Comment by pauloborba** [comment]
@jvcoutinho could you please verify @gaabs solution?

**Comment by jvcoutinho** [comment]
@pauloborba esse bug foi corrigido pelo PR #81
