### ISSUE TITLE
Envio de Logs para estudo de repositório privado

### ISSUE THREAD

**Issue by prga** [guilhermejccavalcanti/jFSTMerge#53]
@guilhermejccavalcanti , @gaabs  e @jvcoutinho. Pessoal, vocês poderiam, por favor, me enviar os logs dos repositórios locais de vocês? Estamos precisando pra testar nossos scripts para o estudo de repositórios privados. É só ir na pasta .git do repositório do jFSTMerge, zipar a pasta logs e me enviar por email.

**Comment by pauloborba** [comment]
@prga pra começar, está OK. podemos tentar de novo em uns 10 dias, quando teremos integrado algumas contribuições que estão pendentes

**Comment by guilhermejccavalcanti** [comment]
@prga https://drive.google.com/file/d/1l8mZdwtwtWLCZX7BbCuavWk1lf83usgC/view?usp=sharing

**Comment by prga** [comment]
@guilhermejccavalcanti será que mandasse o log do repositório certo? Só tinha três linhas no teu arquivo.

**Comment by guilhermejccavalcanti** [comment]
Sim. Mas de qualquer modo, não deve ser útil porque minha versão do S3M não é a mais recente daqui, é de antes de os meninos começarem trabalhar no projeto. E estável e ajustado para os meus experimentos.
Então não espere encontrar conflitos já que só que trabalhava nisso.

**Comment by guilhermejccavalcanti** [comment]
Minha versão oficial é a branch master de uma versão antiga do S3M. O
porquê de os logs estarem vazios não faço idéia.

Em qua, 10 de out de 2018 14:23, Paulo Borba <notifications@github.com>
escreveu:
