### ISSUE TITLE
Verificar se o S3M usa o tipo de retorno de funções como parte de seu match

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#54]

**Comment by pauloborba** [comment]
principalmente para analisar situacao quando dois desenvolvedores alteram o tipo de retorno da mesma declaracao de metodo.

**Comment by pauloborba** [comment]
e verificar como isso tem impactado a contabilizacao de FP/FN, e depois dar retorno para Deyvson e Ricardo.

**Comment by guilhermejccavalcanti** [comment]
não usa não, pessoal. Por exemplo, para um método:

public ModelAndView listStudyUserLogged(HttpServletResponse response) {
...
}

a informação usada no matching é  ```listStudyUserLogged(HttpServletResponse)``` como nome, o ```MethodDecl``` como tipo

**Comment by pauloborba** [comment]
jóia @guilhermejccavalcanti! @jvcoutinho isso já é suficiente para chegarmos a uma conclusão do que aconteceu?

**Comment by pauloborba** [comment]
@jvcoutinho mas se a única mudança foi no tipo de retorno, era para dar conflito nas duas ferramentas

**Comment by pauloborba** [comment]
@jvcoutinho

**Comment by jvcoutinho** [comment]
Fiz alguns testes e descobri o motivo. 

Neste teste, ambos os desenvolvedores mudaram o tipo de retorno do método `initGraph`: de `Graph` para `FourColorableGraph` e `PlanarGraph`, respectivamente.

![conflict](https://user-images.githubusercontent.com/27645414/48424860-597ca980-e742-11e8-8b3e-571d1c6b9c4c.png)

A ferramenta reportou um conflito, mas não houve atuação de nenhum handler (incluindo o de renaming, que se suspeitava inicialmente). Acontece que o tipo de retorno do método também está presente no "corpo" do método, que é usado para o merge não-estruturado, mas isso não é processado depois.

![conflict](https://user-images.githubusercontent.com/27645414/48424677-db200780-e741-11e8-83bd-08b2fdbc9675.png)

Desse modo, se o não-estruturado reporta conflito no retorno do método, o semiestruturado necessariamente também reporta.

**Comment by guilhermejccavalcanti** [comment]
Isso mesmo @jvcoutinho

**Comment by pauloborba** [comment]
@jvcoutinho o que você quer dizer com " mas isso não é processado depois."?

**Comment by jvcoutinho** [comment]
Nenhuma verificação adicional é feita no tipo de retorno depois.

Em ter, 13 de nov de 2018 16:53, Paulo Borba <notifications@github.com
escreveu:
