### ISSUE TITLE
Verificar possível bug com o merge de classes internas

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#55]
Um desenvolvedor alterou o nome de uma classe e adicionou elementos a ela. Outro desenvolvedor alterou o tipo de um atributo para o nome anterior da classe. O resultado do merge do S3M ignora esta mudança.

**Comment by pauloborba** [comment]
aparentemente, o s3m manteve as duas classes (uma com o novo nome, a outra com o nome antigo), e nao incluiu o atributo com o novo tipo (acho que o novo tipo é a nova classe, nao a antiga @jvcoutinho).

**Comment by guilhermejccavalcanti** [comment]
preciso de um cenário/exemplo desses para analisar

**Comment by pauloborba** [comment]
Left: cria classe EstatusType e na classe User modifica o tipo do atributo statusType de StatusType para EstatusType

Right: Adiciona código logo após o atributo statusType na classe User. A linha logo após tem um tab seguido de alguns métodos.

Resultado GIT: conflito entre todo o código novo adicionado (cerca de 80 linhas) e a mudança do tipo do atributo

Resultado S3M: Aceita modificação no tipo do atributo para EstatusType e adiciona todos os métodos novos logo após.

O S3M deu a saida correta mesmo.
