### ISSUE TITLE
Nightly build with a larger sample

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#59]
A periodic test could be applied to: 

1. Identify if merge results remain the same. This could be both a summary check at the end, or a more detailed verification.
2. Guarantee no errors are thrown

The idea is to run tests daily/weekly with a large sample, which is not viable for every build, depending on the sample size.

**Comment by pauloborba** [comment]
good idea @gaabs! 

@guilhermejccavalcanti you already have this kind of test with a larger sample, right? we just need to integrate it to the repositoy, and add it to the travis pipeline, @jvcoutinho .

**Comment by guilhermejccavalcanti** [comment]
I don't @pauloborba.
@gaabs we can use the sample I gave you to evaluate your handler, but is quite big (1700  merge scenarios from 25 java projects), where we would store that?

**Comment by gaabs** [comment]
Well, we could store the samples on another repository. This repository could be cloned before the test.

**Comment by pauloborba** [comment]
@jvcoutinho has this been finished?

**Comment by jvcoutinho** [comment]
Yes, I think the build runs every wednesday.
