### ISSUE TITLE
Renaming Handler False Positive bug

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#65]
It was observed that when both LEFT and RIGHT add the same methods, the renaming handler does not properly match those methods, having False Positives. It was both observed on current master revision and on an older revision (a3a0a2b).

Screenshots attached below:
<br>

<p align="center">LEFT | BASE | RIGHT</p>

![parents](https://user-images.githubusercontent.com/8092225/47608025-33df6880-d9fe-11e8-92a2-17aa85f23535.png)
<br>

<p align="center">S3M | UNSTRUCTURED</p>

![multiple](https://user-images.githubusercontent.com/8092225/47608028-3772ef80-d9fe-11e8-8e09-7151cb3b7d99.png)
<br>

Revisions file used: [graylog-revision.zip](https://github.com/guilhermejccavalcanti/jFSTMerge/files/2522096/graylog-revision.zip)

**Comment by guilhermejccavalcanti** [comment]
False negative? The handler matched and conflicted the single line methods
because they are textually similar although the names suggest they are
different. Do you mean false positive?



Em sáb, 27 de out de 2018 15:49, Giovanni Barros <notifications@github.com>
escreveu:

**Comment by gaabs** [comment]
I have found the bug cause. It is a mutual renaming False Positive. 

This happens because, currently, the mutual renaming handling searches for methods with same body and different signature. It should also check if there exists a method on both sides with same body and same signature.

**Comment by pauloborba** [comment]
good @gaabs. @jvcoutinho have a look at that, please.

**Comment by pauloborba** [comment]
@jvcoutinho could please verify if this has been properly solved by @gaabs?

**Comment by jvcoutinho** [comment]
@pauloborba esse bug foi corrigido pelo PR #81
