### ISSUE TITLE
Travis build considering different OS

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#68]

**Comment by jvcoutinho** [comment]
@pauloborba @guilhermejccavalcanti, I have to modify the shell tests to setup Travis for Windows. I think this is a good opportunity to eliminate them. I can rewrite them as JUnit tests and maintain at least the Git integration test for the installer. Do you agree with that?

**Comment by jvcoutinho** [comment]
Also, probably it's worth to solve #87 in order to setup Travis for Mac OS, since git lfs is not installed by default and the build is crashing because of that.

**Comment by pauloborba** [comment]
> Also, probably it's worth to solve #87 in order to setup Travis for Mac OS, since git lfs is not installed by default and the build is crashing because of that.

makes sense to me

**Comment by pauloborba** [comment]
> @pauloborba @guilhermejccavalcanti, I have to modify the shell tests to setup Travis for Windows. I think this is a good opportunity to eliminate them. I can rewrite them as JUnit tests and maintain at least the Git integration test for the installer. Do you agree with that?

OK, provided the semantics is the same.

**Comment by pauloborba** [comment]
but they should be invoked by the installer. so that we still have tests for the development team, and tests to the users (system testing)---to make sure that the tool was properly installed in their environment.

**Comment by pauloborba** [comment]
@guilhermejccavalcanti can we accept the associated PR and close the issue?

**Comment by guilhermejccavalcanti** [comment]
@jvcoutinho  there is still merge conflicts, so I cannot merge the PR.
