### ISSUE TITLE
Inconsistency in textual merge 

### ISSUE THREAD

**Issue by guilhermejccavalcanti** [guilhermejccavalcanti/jFSTMerge#74]
Textual merge is reporting different results for the same situation. Consider the following merge case:
LEFT:
```java
void m(){
	x = 1;
	y = 0;
	
	int c;
	
	int z = 1;
}
```

BASE:
```java
void m(){
	x = 0;
	y = 0;
	
	int c;
	
	int z = 0;
}
```

RIGHT:
```java
void m(){
	x = 0;
	y = 1;
	
	int c;
	
	int z = 2;
}
```

Textual merge reports either: 

```java
void m(){
<<<<<<< 
		x = 0;
		y = 1;
=======
		x = 1;
		y = 0;
>>>>>>>
		
		int c;
		
<<<<<<< 
		int z = 1;
=======
		int z = 2;
>>>>>>> 
	}
```

and

```java
<<<<<<< MINE
void m(){
		x = 0;
		y = 1;
		
		int c;
		
		int z = 1;
=======
void m(){
		x = 1;
		y = 0;
		
		int c;
		
		int z = 2;
>>>>>>> YOURS
	}
```

This happens with JGit and comand line git merge, but not with standalone diff3 tools.

**Comment by pauloborba** [comment]
@guilhermejccavalcanti that's weird. do you mean it is nondeterministic? some invocations of merge return the first result and others return the second?

**Comment by guilhermejccavalcanti** [comment]
Yes. But in a particular case... Better explain in a meeting. It leads do
differences between semistructured and unstructured merge, which impact
some metrics such as false negatives and even consecutive lines

Em sex, 23 de nov de 2018 12:30, Paulo Borba <notifications@github.com
escreveu:

**Comment by guilhermejccavalcanti** [comment]
As a matter of fact, there is a proof of that non-determinism in the paper of Khanna et al. (https://link.springer.com/chapter/10.1007/978-3-540-77050-3_40)

![image](https://user-images.githubusercontent.com/3333981/48952281-ca814580-ef28-11e8-808d-e08608396eaa.png)

**Comment by pauloborba** [comment]
@guilhermejccavalcanti non-determinism implies different results for the *same* input. the stability property focuses on *similar* inputs. that's different.

**Comment by pauloborba** [comment]
there is indeed lack of stability, but not non-determinism
