### ISSUE TITLE
Add javadoc explaining rename handlers

### ISSUE THREAD

**Issue by guilhermejccavalcanti** [guilhermejccavalcanti/jFSTMerge#78]
For each renaming handler, add a one or two lines comment explaining what that handler does. For instance, for the ```SafeSingleRenamingHandler``` it could be  _"This handler only reports a renaming conflict when unstructured merge reports a conflict with the signature of the renamed declaration"_.

**Comment by pauloborba** [comment]
@jvcoutinho has this been done in your version of the code?

**Comment by jvcoutinho** [comment]
I've commented what the general handler does, not the "specific" implementations. 
But except for Safe, their names are pretty intuitive: merge methods and keep both methods.
