### ISSUE TITLE
Rever implementação do renaming handler

### ISSUE THREAD

**Issue by pauloborba** [guilhermejccavalcanti/jFSTMerge#80]

**Comment by jvcoutinho** [comment]
Tabela de Parnas a ser analisada:
![tabela](https://user-images.githubusercontent.com/27645414/56477108-79926080-6478-11e9-8446-a0c839e1760e.PNG)

**Comment by jvcoutinho** [comment]
Nova Tabela de Parnas:
![parnas](https://user-images.githubusercontent.com/27645414/57247241-b08a7980-7015-11e9-9560-ca79227f1a3b.PNG)

**Comment by pauloborba** [comment]
> Nova Tabela de Parnas:
> ![parnas](https://user-images.githubusercontent.com/27645414/57247241-b08a7980-7015-11e9-9560-ca79227f1a3b.PNG)

**Comment by pauloborba** [comment]
@guilhermejccavalcanti verifica essa tabela, por favor. essa é a semântica pretendida para as operações. tem algumas diferenças em relação a implementação atual. verifica se você discorda de alguma dessas especificações.

**Comment by jvcoutinho** [comment]
@pauloborba isso aqui foi finalizado, PR #81

**Comment by pauloborba** [comment]
OK @jvcoutinho. queria fechar apenas uns detalhes que enviei por email.

**Comment by pauloborba** [comment]
@jvcoutinho is the May 6 table the latest one?

**Comment by jvcoutinho** [comment]
@pauloborba Yes.

**Comment by pauloborba** [comment]
@jvcoutinho introduce old handler as a configuration option

**Comment by pauloborba** [comment]
document detailing handlers effects: https://docs.google.com/document/d/1cMwIxbeW8SwZzMWvMdkWEsShOdIRPuahBDtOcmgyqxc/edit?usp=sharing

**Comment by pauloborba** [comment]
@guilhermejccavalcanti is the associated PR now OK? can we close this issue?
