### ISSUE TITLE
A signature check is crashing the program

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#82]
As reported by @guilhermejccavalcanti, there is a case where `signature.indexOf(name)` is returning -1 (not found).
https://github.com/guilhermejccavalcanti/jFSTMerge/blob/e212b39368a684417ef9925effb326fb7f180304/src/main/java/br/ufpe/cin/mergers/util/RenamingUtils.java#L198-L200

**Comment by jvcoutinho** [comment]
@guilhermejccavalcanti, você pode me passar a lista de repositórios que você minerou (ou se souber o repositório que causou o erro, é ainda melhor)?

**Comment by jvcoutinho** [comment]
@pauloborba @guilhermejccavalcanti Encontrei o erro. Vou explicá-lo.

```
@GET
@Path("max/{campo}")
@Produces("application/json")
public String maxREST(@PathParam("campo") String campo, @Context UriInfo uriInfo) {
    return "{ \"max\": " + super.max(campo, uriInfo) + "}";
}
```
O projeto que minerei usa construções como acima.
Para pegar a assinatura do método, o programa busca o primeiro `{` (que demarcaria o início do corpo). Porém, ele é usado na 2ª linha, quebrando a lógica.

**Comment by pauloborba** [comment]
ótimo João!

parecido com os casos especiais do algoritmo de renaming, que discutimos hoje.

por que é mesmo que você não pega a assinatura via a árvore criada pelo s3m?

**Comment by jvcoutinho** [comment]
> por que é mesmo que você não pega a assinatura via a árvore criada pelo s3m?

Eu busco saber se o prefixo (modificadores, tipo de retorno) e o sufixo (argumentos) dos métodos a serem comparados são iguais. A assinatura na árvore só me dá o sufixo.

**Comment by guilhermejccavalcanti** [comment]
Mas em Java isso não o suficiente para dizer que a assinatura é a mesma?

O método soma(INT a, INT b), teria no fst algo do tipo soma(INT,INT) pelo
que lembro. Isso não é suficiente?

Em qui, 4 de jul de 2019 17:15, João Victor <notifications@github.com>
escreveu:

**Comment by guilhermejccavalcanti** [comment]
Pelo menos no JDT do eclipse é assim tb.

Em qui, 4 de jul de 2019 17:19, Guilherme Cavalcanti <gjcc@cin.ufpe.br>
escreveu:

**Comment by pauloborba** [comment]
Sim, isso deveria ser suficiente (assumindo que trabalhamos com programas Java válidos).

**Comment by jvcoutinho** [comment]
Ok, mudarei então. Já já lanço um PR.

**Comment by jvcoutinho** [comment]
Bem, isso resolve o problema da assinatura. Mas quando buscamos por corpos iguais/similares, usamos a mesma estratégia. Uma alternativa segura é alterar a árvore de parsing para fornecer o corpo também, uma vez que buscar por símbolos parece suscetível a erros como acima. Vocês sugerem algo?

**Comment by pauloborba** [comment]
No momento da criação de um nó correspondente a uma declaração de método, o s3m não já tem as informações separadas (anotações, assinatura, corpo?)?

Se tem, só é armazenar-las em atributos diferentes do nó.

Se não tem, teria que fazer o parsing mais detalhado. Mas ele já deve ter feito isso antes.

**Comment by jvcoutinho** [comment]
>  (anotações, assinatura, corpo?)

Tem tudo isso em um atributo só. Seria interessante separar, até porque dá pra atacar o problema das anotações depois (a issue #42 fala sobre isso).

**Comment by pauloborba** [comment]
Certo. Mas, durante o parsing, ele deve ter essas informações separadas e decidiu concatená-las em um mesmo atributo. Poderia ter colocado em atributos separados. Tem que analisar, e eventualmente mudar, o código que cria os nós.

**Comment by jvcoutinho** [comment]
Ei, vocês não se confundiram ao dizer que a assinatura armazenada no nó da árvore contém o tipo de retorno, não? Ao meu ver, ele só duplica mesmo.

![test](https://user-images.githubusercontent.com/27645414/60893461-58e7d480-a237-11e9-945d-b4f9c431df07.JPG)
![nome](https://user-images.githubusercontent.com/27645414/60893464-58e7d480-a237-11e9-8a87-c3f659dde468.JPG)

**Comment by guilhermejccavalcanti** [comment]
Hum, pode ser que eu tenha confundindo.
Faz mais alguns testes, pega métodos reais, com assinaturas grandes e tal
pra confirmar.

Em ter, 9 de jul de 2019 às 10:51, João Victor <notifications@github.com>
escreveu:

**Comment by jvcoutinho** [comment]
Acho que é isso mesmo, @guilhermejccavalcanti.

![nome2](https://user-images.githubusercontent.com/27645414/60896946-964f6080-a23d-11e9-9638-2c35ad7c75d0.JPG)
![method2](https://user-images.githubusercontent.com/27645414/60896947-964f6080-a23d-11e9-9efb-ea2787e45c0c.JPG)
![nome3](https://user-images.githubusercontent.com/27645414/60896948-964f6080-a23d-11e9-8de5-b047c9a178e9.JPG)
![method3](https://user-images.githubusercontent.com/27645414/60896950-96e7f700-a23d-11e9-9dae-6a60c24cf23a.JPG)
![nome4](https://user-images.githubusercontent.com/27645414/60896953-96e7f700-a23d-11e9-81ee-71f522c53eab.JPG)
![method4](https://user-images.githubusercontent.com/27645414/60896945-964f6080-a23d-11e9-9a92-75f7ba200cab.JPG)

**Comment by guilhermejccavalcanti** [comment]
Tranquilo!

Em ter, 9 de jul de 2019 às 11:35, João Victor <notifications@github.com>
escreveu:
