### ISSUE TITLE
The log file is never closed

### ISSUE THREAD

**Issue by jvcoutinho** [guilhermejccavalcanti/jFSTMerge#97]
Making it impossible to delete if JFSTMerge class is currently active on the JVM (from tests, for example).

Adding a try-finally should be enough to fix this.

**Comment by jvcoutinho** [comment]
About this, I've read the Logger class closes the file automatically when JVM is shutdown.
Unfortunately, this means we can't manipulate the log's directory from tests if main class is instantiated, but it isn't a resource leak.

**Comment by pauloborba** [comment]
OK, but it seems reasonable to open-close whenever needed, instead of leaving it open all the time.
